# arxivの学問領域の指定
subject: cat:math.* OR cat:q-fin.*
# 検索キーワード
keywords:
        kaggle: 1
        trade: 3
        trading: 3
        market: 3
        quant: 2
        stochastic: 2
        mathematica: 1
        maple: 1
        Lattice Gauge: 1
        Lattice: 1
        vertex operator: 1
        

# 通知の閾値
score_threshold: 0
