# arxivの学問領域の指定
subject: cat:math.* OR cat:q-fin.*
# 検索キーワード
keywords:
        Time Series: 3
        Financial: 3
        trade: 3
        market: 3
        algorithmic: 3
        quant: 2
        stochastic: 2
        Lattice Gauge: 1
        Lattice: 1
        vertex operator: 1
        affine: 1
        Lie algebra: 1
        

# 通知の閾値
score_threshold: 0
